### ISSUE TITLE
Not able to clone repository

### ISSUE THREAD

**Issue by spatialillusions** [agcgeoint/rbt#1]
I'm not able to clone the repository, I get the following error message:
`Error downloading object: data/hillshade_europe.mbtiles (79081fb): Smudge error: Error downloading data/hillshade_europe.mbtiles (79081fb472633d1030c38efe6d4c2e0ac2533ccd46821706189aca7cf8f30e3c): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.`

**Comment by mjj203** [comment]
AGC needs to pay the $5/mo to increase the data plan, otherwise one person cloning the repo will max out the bandwidth each month on the free tier. I couldn't fork the repo, but I was able to take an archive and re-create on my personal account. Try cloning from here https://github.com/mjj203/agc-rbt.git.
